# Generated by Django 3.2.5 on 2021-12-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontexts', '0011_alter_webpath_options'),
        ('unicms_calendar', '0002_remove_event_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendarcontext',
            unique_together={('webpath', 'calendar')},
        ),
    ]
