# Generated by Django 3.2.5 on 2022-01-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_calendar', '0003_alter_calendarcontext_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together=set(),
        ),
    ]
