# Generated by Django 3.2.5 on 2022-01-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_calendar', '0005_alter_calendarcontext_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
