# Generated by Django 3.2.5 on 2022-02-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmspublications', '0022_auto_20220128_1536'),
        ('unicms_calendar', '0007_alter_calendar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='publication',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cmspublications.publication'),
            preserve_default=False,
        ),
    ]
