# Generated by Django 3.2.5 on 2022-03-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unicms_calendar', '0008_alter_event_publication'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together={('event', 'calendar')},
        ),
    ]
