# Generated by Django 4.2.7 on 2023-11-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "unicms_calendar",
            "0012_alter_calendar_created_by_alter_calendar_modified_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
