# Generated by Django 4.2.7 on 2023-11-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("unicms_calendar", "0013_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="calendarlocalization",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
